# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/roman/clion-2016.3.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/roman/clion-2016.3.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roman/pb171/pb173-test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roman/pb171/pb173-test/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/roman/clion-2016.3.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/roman/clion-2016.3.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/pb171/pb173-test/cmake-build-debug/CMakeFiles /home/roman/pb171/pb173-test/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/pb171/pb173-test/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named travis_test

# Build rule for target.
travis_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 travis_test
.PHONY : travis_test

# fast build rule for target.
travis_test/fast:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/build
.PHONY : travis_test/fast

#=============================================================================
# Target rules for targets named pb173_test

# Build rule for target.
pb173_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pb173_test
.PHONY : pb173_test

# fast build rule for target.
pb173_test/fast:
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/build
.PHONY : pb173_test/fast

libs/aes.o: libs/aes.c.o

.PHONY : libs/aes.o

# target to build an object file
libs/aes.c.o:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/aes.c.o
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/aes.c.o
.PHONY : libs/aes.c.o

libs/aes.i: libs/aes.c.i

.PHONY : libs/aes.i

# target to preprocess a source file
libs/aes.c.i:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/aes.c.i
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/aes.c.i
.PHONY : libs/aes.c.i

libs/aes.s: libs/aes.c.s

.PHONY : libs/aes.s

# target to generate assembly for a file
libs/aes.c.s:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/aes.c.s
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/aes.c.s
.PHONY : libs/aes.c.s

libs/aesni.o: libs/aesni.c.o

.PHONY : libs/aesni.o

# target to build an object file
libs/aesni.c.o:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/aesni.c.o
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/aesni.c.o
.PHONY : libs/aesni.c.o

libs/aesni.i: libs/aesni.c.i

.PHONY : libs/aesni.i

# target to preprocess a source file
libs/aesni.c.i:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/aesni.c.i
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/aesni.c.i
.PHONY : libs/aesni.c.i

libs/aesni.s: libs/aesni.c.s

.PHONY : libs/aesni.s

# target to generate assembly for a file
libs/aesni.c.s:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/aesni.c.s
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/aesni.c.s
.PHONY : libs/aesni.c.s

libs/sha512.o: libs/sha512.c.o

.PHONY : libs/sha512.o

# target to build an object file
libs/sha512.c.o:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/sha512.c.o
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/sha512.c.o
.PHONY : libs/sha512.c.o

libs/sha512.i: libs/sha512.c.i

.PHONY : libs/sha512.i

# target to preprocess a source file
libs/sha512.c.i:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/sha512.c.i
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/sha512.c.i
.PHONY : libs/sha512.c.i

libs/sha512.s: libs/sha512.c.s

.PHONY : libs/sha512.s

# target to generate assembly for a file
libs/sha512.c.s:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/libs/sha512.c.s
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/libs/sha512.c.s
.PHONY : libs/sha512.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/main.cpp.s
.PHONY : main.cpp.s

securityfunctions.o: securityfunctions.cpp.o

.PHONY : securityfunctions.o

# target to build an object file
securityfunctions.cpp.o:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/securityfunctions.cpp.o
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/securityfunctions.cpp.o
.PHONY : securityfunctions.cpp.o

securityfunctions.i: securityfunctions.cpp.i

.PHONY : securityfunctions.i

# target to preprocess a source file
securityfunctions.cpp.i:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/securityfunctions.cpp.i
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/securityfunctions.cpp.i
.PHONY : securityfunctions.cpp.i

securityfunctions.s: securityfunctions.cpp.s

.PHONY : securityfunctions.s

# target to generate assembly for a file
securityfunctions.cpp.s:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/securityfunctions.cpp.s
	$(MAKE) -f CMakeFiles/pb173_test.dir/build.make CMakeFiles/pb173_test.dir/securityfunctions.cpp.s
.PHONY : securityfunctions.cpp.s

testing.o: testing.cpp.o

.PHONY : testing.o

# target to build an object file
testing.cpp.o:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/testing.cpp.o
.PHONY : testing.cpp.o

testing.i: testing.cpp.i

.PHONY : testing.i

# target to preprocess a source file
testing.cpp.i:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/testing.cpp.i
.PHONY : testing.cpp.i

testing.s: testing.cpp.s

.PHONY : testing.s

# target to generate assembly for a file
testing.cpp.s:
	$(MAKE) -f CMakeFiles/travis_test.dir/build.make CMakeFiles/travis_test.dir/testing.cpp.s
.PHONY : testing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... travis_test"
	@echo "... pb173_test"
	@echo "... libs/aes.o"
	@echo "... libs/aes.i"
	@echo "... libs/aes.s"
	@echo "... libs/aesni.o"
	@echo "... libs/aesni.i"
	@echo "... libs/aesni.s"
	@echo "... libs/sha512.o"
	@echo "... libs/sha512.i"
	@echo "... libs/sha512.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... securityfunctions.o"
	@echo "... securityfunctions.i"
	@echo "... securityfunctions.s"
	@echo "... testing.o"
	@echo "... testing.i"
	@echo "... testing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

